- name: Copying the {{COMPONENT}}repo
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /etc/yum.repos.d/mongodb.repo
    remote_src: yes  

- name: installing {{COMPONENT}}
  ansible.builtin.package:
      name: mongodb-org
      state: present

- name: Starting {{COMPONENT}}
  systemd:
    name: nginx
    state: mongod 
    enabled: yes
    