- name: Play1 
  hosts: all       #groupName in the inventory file
  tasks:
    - name: printing Hello! from task1 of play1
      ansible.builtin.debug:
       msg: "Hello! from task1 of play1"

    - name: printing Hello! from task2 of play1
      ansible.builtin.debug:
       msg: "DevOps Job"