- name: Demo on vars usage
  hosts: all       
  vars:                       # Global Variables : All the tasks of this play can access this variable
   URL: play.google.com
  vars_prompt:
   - name: URNAME
     prompt: Enter your name
     private: false
  tasks:
    - name: printing the variable name
      ansible.builtin.debug:
       msg: Value of the URL is {{URL}}


    - name: demo on using local variables
      ansible.builtin.debug:
       msg: Value of the URL's is {{URL}}
      vars:
       URL: task.google.com
    
#    - name: demo on using undelated variables
#      ansible.builtin.debug:
#       msg: Value of the CLIURL is {{CLIURL}}

    - name: Printing prompt variable
      ansible.builtin.debug:
       msg: Name of the person is {{URNAME}}
   


# NOTE : if you would like to print a variable, then enclose the variable in "{{varName}}" and there is no single quote concept 
#        and if the variables is present in between the string of words, you dont have to enclose them in quotes.

# No two tasks of a play can have a same name.