- name: Demo on Conditions
  hosts: all
  vars:
    action: false
  tasks:
    - name: Run this only when the distrubution is CentOS
      ansible.builtin.debug:
       msg: Welcome to Centos {{ansible_distribution}}
      when: ansible_distribution == "CentOS"

    - name: Run this only when the distrubution is Ubuntu
      ansible.builtin.debug:
       msg: Welcome to Centos {{ansible_distribution}}
      when: ansible_distribution == "Ubuntu"

    - name: Run this action
      ansible.builtin.debug:
       msg: Action is true 
      when: action

    - name: Run this task when the action variable is declared
      ansible.builtin.debug:
       msg: Action variable is declared 
      when: action is not defined
  

