- name: Demo on using  tags
  hosts: all

  tasks:
    - name: This is a frontend task
      ansible.builtin.debug:
       msg: Installing frontend
     tags: frontend

    - name: Starting frontend
      ansible.builtin.debug:
       msg: Installing frontend
      tags: frontend

    - name: This is a backend task
      ansible.builtin.debug:
       msg: Installing Backend
      tags: backend

    - name: Starting backend
      ansible.builtin.debug:
       msg: Starting Backend
      tags: backend

    - name: This is a db task
      ansible.builtin.debug:
       msg: Installing db
      tags: db

    - name: Starting db 
      ansible.builtin.debug:
       msg: Starting db
      tags: db

    