- name: Demo on loops
  hosts: all
  tasks:
    - name: Demo on using loops
      ansible.builtin.debug:
       msg: "Value is "Value is {{item}}"   #item is a key word to represent the value in the list
      loop:
       - 100
       - 300
       - 500

